# Docker compose example for a complete osticket with mysql server and docker secrets for testing purposes.
# DO NOT USE IN PRODUCTION WITHOUT MODIFICATION!
#
---
version: "3.4"
services:
  mariadb:
    image: mariadb
    container_name: osticket-db-1.16.3
    environment:
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: osticketsecret
      MYSQL_ROOT_PASSWORD: osticketsecret
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/backup:/var/lib/backup

  osticket:
    image: osticket:1.16.3
    container_name: osticket-1.16.3
    environment:
      ADMIN_USERNAME: ostadmin
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: osticketsecret
      # Change to en_US or comment out for default language
      LANGUAGE: en_US
      INSTALL_SECRET: mysecret897j98uemlrk09eums09duskd9jpsrds
      ADMIN_PASSWORD: osticketsecret
      # SMTP_HOST: mymailserver.com
    depends_on:
      - mariadb
    ports:
      - "10001:80"
    volumes:
      - ./logs:/var/log/nginx
      - ./data/upload:/data/upload
      - ./data/upload/include/plugins:/data/upload/include/plugins
